// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAziNphu0R5rtAvIug1AyyMRDwbe9_a3A4',
    appId: '1:124752008886:web:054181441bcbd1a06ff817',
    messagingSenderId: '124752008886',
    projectId: 'gringomotopecas-c285e',
    authDomain: 'gringomotopecas-c285e.firebaseapp.com',
    storageBucket: 'gringomotopecas-c285e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjYOPtHUzxuesr9Ec_OtIMHDClOG6aiVo',
    appId: '1:124752008886:android:a3647187c64b25006ff817',
    messagingSenderId: '124752008886',
    projectId: 'gringomotopecas-c285e',
    storageBucket: 'gringomotopecas-c285e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5N1q0a3U0t0xfKO_Y5EydLsWUvzaHQho',
    appId: '1:124752008886:ios:1115638a24307c906ff817',
    messagingSenderId: '124752008886',
    projectId: 'gringomotopecas-c285e',
    storageBucket: 'gringomotopecas-c285e.firebasestorage.app',
    iosBundleId: 'com.example.motogest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAziNphu0R5rtAvIug1AyyMRDwbe9_a3A4',
    appId: '1:124752008886:web:054181441bcbd1a06ff817',
    messagingSenderId: '124752008886',
    projectId: 'gringomotopecas-c285e',
    authDomain: 'gringomotopecas-c285e.firebaseapp.com',
    storageBucket: 'gringomotopecas-c285e.firebasestorage.app',
  );
}
